Eks v2 (#104)
* Adding main with vpc instantiation

Signed-off-by: gar <garlandk@gmail.com>

* Adding eks instantiation

Signed-off-by: gar <garlandk@gmail.com>

* Removing backend store data retrieval

Signed-off-by: gar <garlandk@gmail.com>

* Updating module source

Signed-off-by: gar <garlandk@gmail.com>

* Adding vpc module

Signed-off-by: gar <garlandk@gmail.com>

* Removing test sources

Signed-off-by: gar <garlandk@gmail.com>

* Removing local vpc module

Signed-off-by: gar <garlandk@gmail.com>

* Moving eks module

Signed-off-by: gar <garlandk@gmail.com>

* Updating the location

Signed-off-by: gar <garlandk@gmail.com>

* Removing output

Signed-off-by: gar <garlandk@gmail.com>

* Removing output

Signed-off-by: gar <garlandk@gmail.com>

* Adding terratest

Signed-off-by: gar <garlandk@gmail.com>

* Adding default values

Signed-off-by: gar <garlandk@gmail.com>

* Updating unit test

Signed-off-by: gar <garlandk@gmail.com>

* Adding readme file

Signed-off-by: gar <garlandk@gmail.com>

* Adding unit tests

Signed-off-by: gar <garlandk@gmail.com>

* Updating vpc usage in dev

Signed-off-by: gar <garlandk@gmail.com>

* Adding vscode container runtime

Signed-off-by: gar <garlandk@gmail.com>

* fixing commas

Signed-off-by: gar <garlandk@gmail.com>

* Updating

Signed-off-by: gar <garlandk@gmail.com>

* Adding terraform cloud auth file mount

Signed-off-by: gar <garlandk@gmail.com>

* Adding tags to the node group

Signed-off-by: gar <garlandk@gmail.com>

* Updating tags

Signed-off-by: gar <garlandk@gmail.com>

* Updating gitignore

Signed-off-by: gar <garlandk@gmail.com>

* Parameterizing eks options

Signed-off-by: gar <garlandk@gmail.com>

* Parameterizing additional eks inputs

Signed-off-by: gar <garlandk@gmail.com>

* Parameterizing additional eks inputs

Signed-off-by: gar <garlandk@gmail.com>

* Parameterizing additional eks inputs

Signed-off-by: gar <garlandk@gmail.com>

* Parameterizing additional eks inputs

Signed-off-by: gar <garlandk@gmail.com>

* Parameterizing additional eks inputs

Signed-off-by: gar <garlandk@gmail.com>

* Moving outputs to its own file

Signed-off-by: gar <garlandk@gmail.com>

* Fixing number type

Signed-off-by: gar <garlandk@gmail.com>

* Fixing var

Signed-off-by: gar <garlandk@gmail.com>

* Updating readme

Signed-off-by: gar <garlandk@gmail.com>

* Removing workflows

Signed-off-by: gar <garlandk@gmail.com>

* Adding PR tf pipeline

Signed-off-by: gar <garlandk@gmail.com>

* Removing old files

Signed-off-by: gar <garlandk@gmail.com>

* Adding path

Signed-off-by: gar <garlandk@gmail.com>

* Adding the path it should act on

Signed-off-by: gar <garlandk@gmail.com>

* Updating fmt output

Signed-off-by: gar <garlandk@gmail.com>

* Updating output markdown

Signed-off-by: gar <garlandk@gmail.com>

* Adding working dir to tf apply

Signed-off-by: gar <garlandk@gmail.com>

* fixing output

Signed-off-by: gar <garlandk@gmail.com>

* Updating pipeline name

Signed-off-by: gar <garlandk@gmail.com>

* Ran terraform fmt

Signed-off-by: gar <garlandk@gmail.com>

diff --git a/.github/workflows/terraform-eks-pipeline.yaml b/.github/workflows/terraform-eks-pipeline.yaml
--- a/.github/workflows/terraform-eks-pipeline.yaml
+++ b/.github/workflows/terraform-eks-pipeline.yaml
@@ -1,81 +1,81 @@
-# The name of the pipeline.  Must be unique.
-name: "Terraform - AWS - EKS"
+# # The name of the pipeline.  Must be unique.
+# name: "Terraform - AWS - EKS"
 
-on:
-  push:
-    # only run when files in this path changes
-    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns-1
-    paths:
-    - 'terraform-environments/aws/dev/eks/**'
-    branches:
-      - master
-  pull_request:
-    # only run when files in this path changes
-    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns-1
-    paths:
-    - 'terraform-environments/aws/dev/eks/**'
+# on:
+#   push:
+#     # only run when files in this path changes
+#     # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns-1
+#     paths:
+#     - 'terraform-environments/aws/dev/eks/**'
+#     branches:
+#       - master
+#   pull_request:
+#     # only run when files in this path changes
+#     # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns-1
+#     paths:
+#     - 'terraform-environments/aws/dev/eks/**'
 
-jobs:
-  terraform:
-    name: "Terraform"
-    runs-on: ubuntu-latest
-    env:
-      working-directory: ./terraform-environments/aws/dev/eks/
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+# jobs:
+#   terraform:
+#     name: "Terraform"
+#     runs-on: ubuntu-latest
+#     env:
+#       working-directory: ./terraform-environments/aws/dev/eks/
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v2
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v1
-        with:
-          # terraform_version: 0.13.0:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v1
+#         with:
+#           # terraform_version: 0.13.0:
+#           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-      - name: Terraform Format
-        id: fmt
-        working-directory: ${{env.working-directory}}
-        run: terraform fmt -check
+#       - name: Terraform Format
+#         id: fmt
+#         working-directory: ${{env.working-directory}}
+#         run: terraform fmt -check
 
-      - name: Terraform Init
-        id: init
-        working-directory: ${{env.working-directory}}
-        run: terraform init
+#       - name: Terraform Init
+#         id: init
+#         working-directory: ${{env.working-directory}}
+#         run: terraform init
 
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        working-directory: ${{env.working-directory}}
-        run: terraform plan -no-color
-        continue-on-error: true
+#       - name: Terraform Plan
+#         id: plan
+#         if: github.event_name == 'pull_request'
+#         working-directory: ${{env.working-directory}}
+#         run: terraform plan -no-color
+#         continue-on-error: true
 
-      - uses: actions/github-script@0.9.0
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            <details><summary>Show Plan</summary>
-            \`\`\`
-            ${process.env.PLAN}
-            \`\`\`
-            </details>
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+#       - uses: actions/github-script@0.9.0
+#         if: github.event_name == 'pull_request'
+#         env:
+#           PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+#         with:
+#           github-token: ${{ secrets.GITHUB_TOKEN }}
+#           script: |
+#             const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+#             #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+#             #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+#             <details><summary>Show Plan</summary>
+#             \`\`\`
+#             ${process.env.PLAN}
+#             \`\`\`
+#             </details>
+#             *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
               
-            github.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+#             github.issues.createComment({
+#               issue_number: context.issue.number,
+#               owner: context.repo.owner,
+#               repo: context.repo.repo,
+#               body: output
+#             })
+#       - name: Terraform Plan Status
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-        working-directory: ${{env.working-directory}}
-        run: terraform apply -auto-approve
+#       - name: Terraform Apply
+#         if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+#         working-directory: ${{env.working-directory}}
+#         run: terraform apply -auto-approve
